config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/index/:lecture_type' => "home#index"
  get '/home/index' => 'home#index'
  get 'mockInitialize' => "home#mock"
  get 'initialize' => "home#init"

  get '/tutor/new' => "tutor#new"
  post '/tutor' => "tutor#create"

  get '/schedule/update' => "home#update"
  get '/schedule/new' => "schedule#new"
  post '/schedule' => "schedule#addSchedule"
  patch '/schedule' => "home#updateSchedule"
  delete 'schedule/:schedule_id/delete' => 'home#deleteSchedule', as: 'schedule_delete'
  get '/schedule/:schedule_id/delete' => 'home#deleteSchedule'
end

app/controllers/home_controller.rb
require 'matrix'
class HomeController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @schedules = Schedule.all
    @lecture_type = params[:lecture_type]

    start_date = params[:start_date]
    if start_date.blank?
      @start_date = DateTime.now
    else
      @start_date = DateTime.parse(start_date)
    end

    date_range = (@start_date.beginning_of_week..@start_date.end_of_week).to_a
    hour_range = (@start_date.localtime.beginning_of_day.to_i..@start_date.localtime.end_of_day.to_i).step(30.minutes)


    list_of_schedules = Schedule.where(active:1, :start_date => (@start_date.beginning_of_week)..(@start_date.end_of_week)).order(start_date: :asc)

    query = <<-SQL
      WITH t AS (
        SELECT *, start_date, LEAD(start_date, 1) OVER (PARTITION BY tutor_id ORDER BY start_date ASC) AS next_available_date
        FROM schedules 
        WHERE active = 1
      )     

      SELECT *
      FROM t
      WHERE DATETIME(next_available_date, '-30 MINUTE') = t.start_date
    SQL
    list_of_schedules_40 = list_of_schedules.select('*').from("(#{query} )AS schedules")

    range_by_hour = (@start_date.localtime.beginning_of_day.to_datetime.to_i .. @start_date.localtime.end_of_day.to_datetime.to_i).step(30.minutes)
    range_by_day = (@start_date.beginning_of_week.to_datetime.to_i .. @start_date.end_of_week.to_datetime.to_i).step(1.day)
    @active = Array.new(hour_range.size) { Array.new(date_range.size) { false } }

    if @lecture_type == "mock" || @lecture_type == "init"
      return
    end

    calendar_array = Array.new(range_by_hour.size) { Array.new(range_by_day.size) { false } }
    range_by_hour.each_with_index do |hour, row|
      range_by_day.each_with_index do |day, column|
        calendar_array[row][column] = DateTime.new(Time.at(day).year, Time.at(day).month, Time.at(day).day, Time.at(hour).hour, Time.at(hour).min, Time.at(hour).sec, Time.at(hour).zone)
      end
    end

    case @lecture_type
    when "20" then
      list_of_schedules.map{ |s|
        active_index = Matrix[*calendar_array].index(s.start_date)
        @active[active_index[0]][active_index[1]] = true
      }
    when "40" then
      list_of_schedules_40.map{ |s|
        active_index = Matrix[*calendar_array].index(s.start_date)
        @active[active_index[0]][active_index[1]] = true
      }
    else
    end
  end

  def update
    @tutors = Tutor.all
    if @tutors.blank?
      @tutors = nil
    end
    tutor_id = params[:tutor_id]
    @s_id= params[:schedule_id]
    @edit_mode = params[:edit_mode]
    @tutor = Tutor.find_by(id: tutor_id)
    @schedules = Schedule.where(tutor_id: tutor_id).order(start_date: :asc)
    if @schedules.blank?
      @schedules = nil
    end
    @schedule = Schedule.find_by(id: @s_id, tutor_id: tutor_id)
  end

  def updateSchedule
    _active = params[:schedule][:active]
    _schedule = Schedule.find(params[:s_id])
    _schedule.active = _active
    _schedule.save
    redirect_to "/schedule/update/?tutor_id=#{params[:t_id]}&schedule_id=#{params[:s_id]}"
  end

  def deleteSchedule
    Schedule.destroy(params[:schedule_id])
    redirect_to '/schedule/update'
  end

  def mock
    Tutor.delete_all
    Schedule.delete_all
    Tutor.new(
      name: 'tutor Choi'
    ).save
    Tutor.new(
      name: 'tutor Kim'
    ).save
    Tutor.new(
      name: 'tutor So'
    ).save
    Tutor.new(
      name: 'tutor lucy'
    ).save
    Tutor.new(
      name: 'tutor Park'
    ).save
    Tutor.new(
      name: 'tutor Lee'
    ).save
    Tutor.new(
      name: 'tutor Gon'
    ).save
    Tutor.new(
      name: 'tutor Paik'
    ).save

    Schedule.new(
      start_date: '2022-2-28 00:00:00',
      tutor_id: 1,
      active: 2
    ).save

    Schedule.new(
      start_date: '2022-2-28 00:30:00',
      tutor_id: 1,
      active: 2
    ).save

    Schedule.new(
      start_date: '2022-2-28 01:00:00',
      tutor_id: 1,
      active: 2
    ).save

    Schedule.new(
      start_date: '2022-2-28 01:30:00',
      tutor_id: 1,
      active: 2
    ).save

    Schedule.new(
      start_date: '2022-2-28 02:00:00',
      tutor_id: 1,
      active: 2
    ).save

    Schedule.new(
      start_date: '2022-2-28 01:00:00',
      tutor_id: 2,
      active: 1
    ).save

    Schedule.new(
      start_date: '2022-2-28 01:30:00',
      tutor_id: 2,
      active: 1
    ).save

    Schedule.new(
      start_date: '2022-2-28 02:00:00',
      tutor_id: 2,
      active: 1
    ).save

    Schedule.new(
      start_date: '2022-2-28 04:00:00',
      tutor_id: 2,
      active: 1
    ).save

    Schedule.new(
      start_date: '2022-2-28 04:30:00',
      tutor_id: 2,
      active: 1
    ).save

    Schedule.new(
      start_date: '2022-3-1 00:30:00',
      tutor_id: 3,
      active: 1
    ).save

    Schedule.new(
      start_date: '2022-3-1 01:00:00',
      tutor_id: 3,
      active: 1
    ).save

    Schedule.new(
      start_date: '2022-3-1 05:00:00',
      tutor_id: 3,
      active: 1
    ).save

    Schedule.new(
      start_date: '2022-3-1 08:00:00',
      tutor_id: 3,
      active: 1
    ).save

    Schedule.new(
      start_date: '2022-3-1 08:30:00',
      tutor_id: 3,
      active: 1
    ).save

    Schedule.new(
      start_date: '2022-3-2 01:30:00',
      tutor_id: 4,
      active: 1
    ).save

    Schedule.new(
      start_date: '2022-3-2 02:00:00',
      tutor_id: 4,
      active: 1
    ).save

    Schedule.new(
      start_date: '2022-3-2 02:30:00',
      tutor_id: 4,
      active: 1
    ).save

    Schedule.new(
      start_date: '2022-3-2 03:00:00',
      tutor_id: 4,
      active: 1
    ).save

    Schedule.new(
      start_date: '2022-3-03 00:00:00',
      tutor_id: 5,
      active: 1
    ).save

    Schedule.new(
      start_date: '2022-3-03 00:30:00',
      tutor_id: 5,
      active: 1
    ).save

    Schedule.new(
      start_date: '2022-3-03 00:30:00',
      tutor_id: 6,
      active: 1
    ).save

    Schedule.new(
      start_date: '2022-3-03 01:00:00',
      tutor_id: 6,
      active: 1
    ).save

    Schedule.new(
      start_date: '2022-3-03 01:30:00',
      tutor_id: 6,
      active: 1
    ).save

    Schedule.new(
      start_date: '2022-3-04 03:30:00',
      tutor_id: 7,
      active: 1
    ).save

    Schedule.new(
      start_date: '2022-3-04 04:00:00',
      tutor_id: 7,
      active: 1
    ).save

    Schedule.new(
      start_date: '2022-2-28 04:00:00',
      tutor_id: 8,
      active: 1
    ).save

    Schedule.new(
      start_date: '2022-3-01 04:00:00',
      tutor_id: 8,
      active: 1
    ).save

    Schedule.new(
      start_date: '2022-3-02 04:00:00',
      tutor_id: 8,
      active: 1
    ).save

    Schedule.new(
      start_date: '2022-2-24 00:00:00',
      tutor_id: 1,
      active: 1
    ).save

    Schedule.new(
      start_date: '2022-2-24 00:30:00',
      tutor_id: 1,
      active: 1
    ).save

    Schedule.new(
      start_date: '2022-2-24 01:00:00',
      tutor_id: 1,
      active: 1
    ).save

    Schedule.new(
      start_date: '2022-2-25 01:30:00',
      tutor_id: 1,
      active: 1
    ).save

    Schedule.new(
      start_date: '2022-2-25 02:00:00',
      tutor_id: 1,
      active: 2
    ).save

    Schedule.new(
      start_date: '2022-3-7 03:00:00',
      tutor_id: 4,
      active: 1
    ).save

    Schedule.new(
      start_date: '2022-3-07 00:00:00',
      tutor_id: 5,
      active: 1
    ).save

    Schedule.new(
      start_date: '2022-3-07 00:30:00',
      tutor_id: 5,
      active: 1
    ).save

    Schedule.new(
      start_date: '2022-3-08 02:30:00',
      tutor_id: 6,
      active: 1
    ).save

    Schedule.new(
      start_date: '2022-3-08 03:00:00',
      tutor_id: 6,
      active: 1
    ).save

    Schedule.new(
      start_date: '2022-3-10 02:30:00',
      tutor_id: 8,
      active: 1
    ).save

    Schedule.new(
      start_date: '2022-3-10 03:00:00',
      tutor_id: 8,
      active: 2
    ).save

    Schedule.new(
      start_date: '2022-3-10 03:30:00',
      tutor_id: 8,
      active: 1
    ).save

    Schedule.new(
      start_date: '2022-3-10 04:00:00',
      tutor_id: 8,
      active: 2
    ).save

    Schedule.new(
      start_date: '2022-3-10 04:30:00',
      tutor_id: 8,
      active: 1
    ).save

    Schedule.new(
      start_date: '2022-3-10 05:00:00',
      tutor_id: 8,
      active: 1
    ).save

    Schedule.new(
      start_date: '2022-3-10 03:30:00',
      tutor_id: 7,
      active: 1
    ).save

    Schedule.new(
      start_date: '2022-3-10 04:00:00',
      tutor_id: 7,
      active: 1
    ).save

    Schedule.new(
      start_date: '2022-3-10 04:30:00',
      tutor_id: 7,
      active: 2
    ).save

    Schedule.new(
      start_date: '2022-3-12 03:30:00',
      tutor_id: 8,
      active: 1
    ).save

    Schedule.new(
      start_date: '2022-3-12 04:00:00',
      tutor_id: 8,
      active: 1
    ).save
    redirect_to '/index/mock'
  end

  def init
    Tutor.delete_all
    Schedule.delete_all
    redirect_to '/index/init'
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/check.html.erb
<h1>temp</h1>

app/views/home/index.html.erb
<html>
<head>
<!--
  Cusco Sky table styles
  written by Braulio Soncco http://www.buayacorp.com
-->
  <style>
      table{
          width: 70%;
          border: 1px solid #D4E0EE;
          border-collapse: collapse;
          font-family: "Trebuchet MS", Arial, sans-serif;
          color: #555;
      }
      th, td {
          width: 10%;
          border: 1px solid #D4E0EE;
          border-collapse: collapse;
          font-family: "Trebuchet MS", Arial, sans-serif;
          color: #555;
      }

      caption {
          font-size: 150%;
          font-weight: bold;
          margin: 5px;
      }

      td, th {
          padding: 4px;
      }

      thead th {
          text-align: center;
          background: #E6EDF5;
          color: #4F76A3;
          font-size: 100% !important;
      }

      tbody th {
          font-weight: bold;
      }

      tbody tr { background: #FCFDFE; }

      tbody tr.odd { background: #F7F9FC; }

      table a:link {
          color: #718ABE;
          text-decoration: none;
      }

      table a:visited {
          color: #718ABE;
          text-decoration: none;
      }

      table a:hover {
          color: #718ABE;
          text-decoration: underline !important;
      }

      tfoot th, tfoot td {
          font-size: 85%;
      }
      .center {
          align-content: center;
          text-align: center;
          margin-left: auto;
          margin-right: auto;
      }
      .active{
          background-color: palegreen;
      }
      .inactive{
          background-color: lightgrey;
      }
  </style>

</head>

<body>

<% start_date = (params[:start_date] || Date.today).to_date %>
<% date_range = (start_date.beginning_of_week..start_date.end_of_week).to_a %>
<% hour_range = (start_date.beginning_of_day.to_i..start_date.end_of_day.to_i).step(30.minutes) %>

<br>
<br>
<div class="center">
  <button type="button"> <%= link_to "Mock Data로 초기화하기", "/mockInitialize"%></button>
  <button type="button"> <%= link_to "초기화하기", "/initialize"%></button>
  <br>
  <br>
  <span>새로 오셨나요? </span><button type="button"><%=link_to "튜터 등록하기", "/tutor/new"%></button>
</div>
<br>

  <table class="center">
    <tr>
      <th>Dear Students</th>
      <th>Dear Tutors</th>
    </tr>
    <tr>
      <td>
        <% if @lecture_type=='20' %>
          <p>현재 선택하신 수강권은 <b>20분 수강권</b>입니다.</p>
        <% elsif @lecture_type=='40' %>
          <p>현재 선택하신 수강권은 <b>40분 수강권</b>입니다.</p>
        <% else%>
          <p>수강권을 선택해주세요</p>
        <% end %>

        <button type="button"> <%= link_to "20분", "/index/20/?start_date=#{start_date}"%></button>
        <button type="button"> <%= link_to "40분", "/index/40/?start_date=#{start_date}"%></button>
      </td>
      <td>
        <p>수업 가능 시간을 업데이트해주세요</p>
        <button type="button"><%=link_to "Update", "/schedule/update"%></button>
        <button type="button"><%=link_to "Create", "/schedule/new"%></button>
      </td>
    </tr>
  </table>
  <br>

<table class="center">
  <thead>
  <tr>
    <td colspan="8" class="center">
      <%=link_to "Previous", start_date: date_range.first - 1.week%>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <%= start_date.year %>, <%= I18n.t("date.month_names")[start_date.month] %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <%= link_to "Next", start_date: date_range.first + 1.week %>
    </td>
  </tr>
  <tr>
    <th>Hour</th>
    <% date_range.slice(0, 7).each do |day| %>
      <th><%= I18n.t("date.abbr_day_names")[day.wday] %> <%= day.strftime('%m/%d') %></th>
    <% end %>
  </tr>
  </thead>
  <tbody>

  <% hour_range.each_with_index do |hour, idx_hour| %>
    <tr>
      <th><%= Time.at(hour).localtime.strftime('%H:%M') %></th>
      <% date_range.each_with_index do |day, idx_day| %>
        <td class= <%= @active[idx_hour][idx_day]==true ? 'active' : 'inactive'  %>>
          <% @matched = @schedules.select{ |s| s.start_date.strftime('%H:%M') == Time.at(hour).localtime.strftime('%H:%M') && day == s.start_date.to_date }%>
          <% if @matched %>
            <%@matched.each do |schedule| %>
                <div><%= schedule.tutor_id %><%= schedule.active==1 ? '(o)' : '(x)' %></div>
            <% end %>
          <% else %>
            <div>x</div>
          <% end %>
        </td>
      <% end %>
    </tr>
  <% end %>
  </tr>
  </tbody>
  <tfoot>
  <tr>
    <td colspan="8" class="center">Enjoy your class!</td>
  </tr>
  </tfoot>
</table>
</body>
</html>

app/views/home/main.html.erb
<div id="scheduler_here" class="dhx_cal_container" style='width:100%; height:800px;'>
  <div class="dhx_cal_navline">
    <div class="dhx_cal_prev_button">&nbsp;</div>
    <div class="dhx_cal_next_button">&nbsp;</div>
    <div class="dhx_cal_today_button"></div>
    <div class="dhx_cal_date"></div>
    <div class="dhx_cal_tab" name="day_tab" style="right:204px;"></div>
    <div class="dhx_cal_tab" name="week_tab" style="right:140px;"></div>
    <div class="dhx_cal_tab" name="month_tab" style="right:76px;"></div>
  </div>
  <div class="dhx_cal_header">
  </div>
  <div class="dhx_cal_data">
  </div>
</div>

<script>
    scheduler.config.xml_date="%Y-%m-%d %H:%i";
    scheduler.init("scheduler_here");
    scheduler.load("/home/data", "json");
    var dp = new dataProcessor("/home/db_action");
    dp.init(scheduler);
    dp.setTransactionMode("GET", false);
    dp.setTransactionMode("POST", true);
</script>

app/views/home/update.html.erb
<html>
<head>
  <!--
    Cusco Sky table styles
    written by Braulio Soncco http://www.buayacorp.com
  -->
  <style>
      table{
          width: 70%;
          border: 1px solid #D4E0EE;
          border-collapse: collapse;
          font-family: "Trebuchet MS", Arial, sans-serif;
          color: #555;
      }
      th, td {
          width: 10%;
          border: 1px solid #D4E0EE;
          border-collapse: collapse;
          font-family: "Trebuchet MS", Arial, sans-serif;
          color: #555;
      }

      caption {
          font-size: 150%;
          font-weight: bold;
          margin: 5px;
      }

      td, th {
          padding: 4px;
      }

      thead th {
          text-align: center;
          background: #E6EDF5;
          color: #4F76A3;
          font-size: 100% !important;
      }

      tbody th {
          font-weight: bold;
      }

      tbody tr { background: #FCFDFE; }

      tbody tr.odd { background: #F7F9FC; }

      table a:link.edit{
          font-weight: bold;
          color: orangered; !important;
      }

      table a:link {
          color: #718ABE;
          text-decoration: none;
      }

      table a:visited {
          color: #718ABE;
          text-decoration: none;
      }

      table a:hover {
          color: #718ABE;
          text-decoration: underline !important;
      }

      tfoot th, tfoot td {
          font-size: 85%;
      }
      .center {
          align-content: center;
          text-align: center;
          margin-left: auto;
          margin-right: auto;
      }
      .active{
          background-color: palegreen;
      }
      .inactive{
          background-color: lightgrey;
      }
      a:link.edit{
          font-weight: bold;
          color: red;
      }
  </style>

</head>
<body class="center">
<br><br><br><br><br><br><br><br><br><br><br><br><br>
<button type="button"> <%= link_to "홈으로 이동", "/"%></button>
<br><br>
<h3>일정 변경/삭제하기</h3>

<%= form_with url: "/schedule/update", method: :get, enforce_utf8: false do |form| %>
  <% if @tutor %>
    <%= form.select :tutor_id,  @tutors.map{|t| [t.name, t.id]}, selected: @tutor.id %>
    <%= submit_tag "튜터 선택", :name => nil %>
    <% if @schedules && @schedule %>
      <%= form_with url: "/schedule/update", method: :get, enforce_utf8: false do |form| %>
        <%= form.select :schedule_id,  @schedules.map{|s| [s.start_date.strftime('%Y-%m-%d %H시 %M분'), s.id]}, selected: @schedule.id %>
        <%= submit_tag "일정 조회하기", :name => nil %>
      <% end %>
    <% elsif @schedules && @s_id.blank?%>
      <%= form_with url: "/schedule/update", method: :get, enforce_utf8: false do |form| %>
        <%= form.select :schedule_id,  @schedules.map{|s| [s.start_date.strftime('%Y-%m-%d %H시 %M분'),  s.id]} %>
        <%= submit_tag "일정 조회하기", :name => nil %>
      <% end %>
    <% else %>
      <p>등록된 일정이 없습니다.</p>
    <% end %>
  <% elsif @tutors%>
    <%= form.select :tutor_id,  @tutors.map{|t| [t.name, t.id]}, selected: @tutor ? @tutor.name : @tutors[0].name %>
    <%= submit_tag "튜터 선택", :name => nil %>
  <% else %>
      <p>등록된 튜터가 없습니다.</p>
  <% end %>
<% end %>

<br>
<table class="center">
<% if @tutor %>
  <tr>
    <th>튜터명</th>
    <td><%= @tutor.name %></td>
  </tr>
      <% if @schedule && @schedule %>

        <% if @edit_mode %>
            <tr>
              <th>일자</th>
              <td><%= @schedule.start_date.strftime('%Y-%m-%d %H시 %M분') %></td>
            </tr>
            <tr>
              <th>가능 여부</th>
              <td>
                  <%= form_with model: @schedule do |form| %>
                    <input name="t_id" type="hidden" value=<%= @tutor.id %>/>
                    <input name="s_id" type="hidden" value=<%= @schedule.id %>/>
                    <%= form.select :active, [["O", 1], ["X", 2]], selected: @schedule.active %><%= submit_tag "저장하기" %>
                  <% end %>
              </td>
            </tr>
        <% else %>
          <tr>
            <th>일자</th>
            <td><%= @schedule.start_date.strftime('%Y-%m-%d %H시 %M분') %></td>
          </tr>
          <tr>
            <th>가능 여부</th>
            <td><%= @schedule.active == 1 ? 'O ' : 'X ' %><button type="button"><%= link_to "수정하기", "/schedule/update?tutor_id=#{@tutor.id}&schedule_id=#{@schedule.id}&edit_mode=true",  class:"edit"%></button></td>
          </tr>
        <% end %>
      <% end %>
  <% end %>
</table>
<br>
<% if !@edit_mode && @schedule %><%= button_to "삭제하기", schedule_delete_path(@schedule), method: :delete, form: {data: {turbo_confirm: '정말로 삭제하시겠어요?'}} %><% end %>
</body>
</html>